kext: fp_getfvpandvid: FIXME: operand of type 'void' where arithmetic or pointer type is required
lib/kern.c:305:22: error: operand of type 'void' where arithmetic or pointer type is required
    uth = (uthread_t)_get_bsdthread_info(th); // returns th->uthread